### PR TITLE
Support ghc-9.4

### PR DESCRIPTION
**Pull request by 4eUeP**

### CODE REVIEW

**Review by Dessix — APPROVED** [review]
This appears to successfully bring support to GHC 9.6.2 as well. I highly recommend review and merge, if any Z-Data maintainers are available to do so.

**Comment by winterland1989** [comment]
The win-CI 9.4 error seems related to its linker, patch look good! As for 9.6 compatibilities, go ahead adding to CI matrix please.

**Review by winterland1989 — APPROVED** [review]

**Comment by Dessix** [comment]
It would appear that something has changed that breaks 9.2's handling of doubles in JSON, since the tests which passed in May?

**Comment by winterland1989** [comment]
Somehow I couldn't remember how these test could pass:
+ `encodeJSON` will directly encode `Double` using `B.double` builder, which in turn uses grisu3, so `0` get printed to `0.0`.
+ `encodeJSON . toValue` will first convert the `Double` field to `Scientific` and print `0` in case of `0`.

This test should be removed IMO.

**Comment by 4eUeP** [comment]
@winterland1989 Yeah, perhaps `[(0 :: Int, 0.0 :: Double)]` had not been generated by  QuickCheck  before.

**Pull request merged**
